# Generated by Django 3.0.5 on 2020-04-16 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('Car_reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Make_model', models.CharField(max_length=50)),
                ('Make_year', models.IntegerField()),
                ('Transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=9)),
                ('Fuel', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=6)),
                ('Kms_driven', models.IntegerField(blank=True)),
                ('Price', models.IntegerField()),
                ('Sitting_capacity', models.CharField(choices=[('5', '5'), ('7', '7')], max_length=1)),
                ('Fareperkm', models.IntegerField(blank=True)),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('GREEN', 'Green'), ('RED', 'Red'), ('BLUE', 'Blue')], max_length=8)),
                ('Image_url', models.URLField(blank=True)),
                ('No_of_rides', models.IntegerField(default=0)),
                ('Fareperhour', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('No_of_bookings', models.IntegerField(default=0)),
                ('Profile_status', models.CharField(choices=[('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED')], default='UNVERIFIED', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License', models.CharField(blank=True, max_length=20, null=True)),
                ('Booked_for_kms', models.IntegerField(blank=True, null=True)),
                ('Ride_start_date', models.DateTimeField(blank=True, null=True)),
                ('Ride_end_date', models.DateTimeField(blank=True, null=True)),
                ('Payment_start_time', models.DateTimeField(auto_now_add=True)),
                ('unique_booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Car_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CarDetails')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make_model', models.CharField(blank=True, max_length=50)),
                ('unique_booking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('License', models.CharField(blank=True, max_length=20)),
                ('Kms_initial', models.IntegerField(blank=True, null=True)),
                ('Kms_later', models.IntegerField(blank=True, null=True)),
                ('Kms_Driven', models.IntegerField(blank=True, null=True)),
                ('Booked_for_kms', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Total_price', models.IntegerField(blank=True, null=True)),
                ('Extra_fare', models.IntegerField(blank=True, null=True)),
                ('Booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Ride_start_date', models.DateTimeField(blank=True, null=True)),
                ('Ride_end_date', models.DateTimeField(blank=True, null=True)),
                ('Ride_started_at', models.DateTimeField(blank=True, null=True)),
                ('Ride_ended_at', models.DateTimeField(blank=True, null=True)),
                ('Final_price', models.IntegerField(blank=True, null=True)),
                ('is_ride_completed', models.BooleanField(default=False)),
                ('Transaction_id', models.CharField(blank=True, max_length=60)),
                ('Bank_txn_id', models.CharField(blank=True, max_length=60)),
                ('Transaction_date', models.CharField(blank=True, max_length=60)),
                ('Car_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CarDetails')),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
