# Generated by Django 3.0.5 on 2020-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='is_ride_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
